### ISSUE TITLE
Support NPM

### ISSUE THREAD

**Issue by ghost** [FontFaceKit/robotodraft#1]
Could you please add a package.json file so that this can be installed using NPM?

**Comment by bardware** [comment]
@gustavohenke npm is your domain :)

**Comment by ghost** [comment]
If I do a pull request, would you merge it in? You don't have to publish to the NPM directory, you just need to add a package.json in the root so NPM can install it from Github.

**Comment by rob3c** [comment]
@chrismbeckett thanks for npm-ifying this!

For the benefit of those googling that land here (until the readme is updated), you install via npm like this:

  `> npm install --save https://github.com/FontFaceKit/robotodraft.git#gh-pages`

**Comment by gustavohenke** [comment]
@rob3c _maybe_ the following works as well (I can't ensure this atm):

``` shell
npm install --save FontFaceKit/robotodraft
```

**Comment by rob3c** [comment]
Thanks, but when I tried that, it threw errors (on Windows, at least). I had to use the branch specifier to get it to work. Use of the npm git repo shorthand syntax would certainly be simpler, though!
